In [2]:
import numpy as np

In [15]:
# 1a
x = np.matrix([[2],[3],[5]])
v = np.matrix([[3],[0],[4]])

xTv = np.matmul(x.transpose(),v)
xvT = np.matmul(x,v.transpose())

print("xTv =", xTv, "xvT =", xvT)

xTv = [[26]] xvT = [[ 6  0  8]
 [ 9  0 12]
 [15  0 20]]


In [18]:
#1b
A = np.matrix([[4,1,0,2],[2,0,1,3]])
b = np.matrix([[3],[0],[5],[1]])

c = np.matmul(A,b)

print("c = Ab", c)

c = [[14]
 [14]]


In [20]:
#1c
B = np.matrix([[3,2,0],[0,4,2],[5,0,1],[1,3,4]])

C = np.matmul(A,B)

print("C = AB =", C)

C = [[14 18 10]
 [14 13 13]]


In [24]:
#1d
w = np.matrix([[2],[4],[3],[1]])

print("||w||_2 =", np.linalg.norm(w))

||w||_2 = 5.477225575051661


In [32]:
#1e
u = np.matrix([[5],[0],[0]])
print("The nit vector norm pointing in the same direction as u =", int(np.linalg.norm(u / np.linalg.norm(u))))

The nit vector norm pointing in the same direction as u = 1


In [38]:
#2b
print("The sub-matrix of B consisting of the elements of only the second and third row, and the second column =", B[1:3][:,1])

The sub-matrix of B consisting of the elements of only the second and third row, and the second column = [[4]
 [0]]


In [64]:
#2c
def dot(v1, v2):
    if len(v1) == len(v2):
        temp = 0
        for i,j in zip(v1,v2):
            temp += i*j
        return temp
    else:
        raise Exception("The lengths of the inputted vectors are not equal.")

In [61]:
#2d
data = np.matrix([[17,9],[21,10],[12,17]])
print("The matrix representation of the subjects' tumor data is", data)

The matrix representation of the subjects' tumor data is [[17  9]
 [21 10]
 [12 17]]


In [79]:
#2e
def transform(data):
    return (np.matmul(data, np.matrix([[1],[1]])))

In [83]:
#2f
def hypothesis(x, theta, theta_0):
    return int(np.matmul(theta.transpose(), x)) + theta_0

subject1 = np.matrix([[17],[9]])
subject2 = np.matrix([[21],[10]])
subject3 = np.matrix([[12],[17]])
subjects = [subject1, subject2, subject3]

for i in subjects:
    print(hypothesis(i, np.matrix([[4],[5]]), -100))

13
34
33
